---
- name: build webapp
  hosts: build
  become: yes

  tasks:
  - name: Ensure tomcat package is pesent
    apt:
      name: tomcat9
      state: present
  
  - name: Ensure default JDK is present
    apt:
      name: default-jdk
      state: present
  
  - name: Ensure maven package is present
    apt:
      name: maven
      state: present
  
  - name: Ensure git package is present
    apt:
      name: git
      state: present
  
  - name: Ensure boxfuse-sample-java-war-hello is present
    git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /home/boxfuse-sample-java-war-hello
      clone: yes

  - name: package boxfuse
    command: mvn -f /home/boxfuse-sample-java-war-hello/pom.xml

- name: open webapp
  hosts: web
  become: yes

  tasks:
  - name: Ensure tomcat package is present
    apt:
      name: tomcat9
      state: present

  - name: Ensure default JDK is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure tomcat started
    apt:
      name: tomcat9
      state: started
  
  - name: Ensure webapp is move it
    synchronize:
      src: /home/boxfuse/target/hello-1.0.war
      dest: /var/lib/tomcat9/webapps

